### ISSUE TITLE
Open in a separate window

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-remotehub#3]
What an awesome idea! When I tried it, it replaced my current workspace with the remote one; I'd prefer if it opened in a new window (with the _RemoteHub: Open GitHub Repository..._ command).

**Comment by eamodio** [comment]
💯% agree -- Right now there isn't a good option for providing that. Here is the open request: https://github.com/Microsoft/vscode/issues/34770

**Comment by eamodio** [comment]
Fixed in 0.5
